---
deployment:
  tasks:
    - /opt/alt/php84/usr/bin/php /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - /opt/alt/php84/usr/bin/php artisan migrate --force
    - /opt/alt/php84/usr/bin/php artisan config:clear
    - /opt/alt/php84/usr/bin/php artisan route:clear
    - /opt/alt/php84/usr/bin/php artisan view:clear